"""Build the localization pull-request body from the run's reports.

CI's last step: turn `plan --report`, the executed queue, and `render --report`
into the Markdown summary a human sees before merging (AC3 — how many segments
were new, revised, reused, and copied; what actually completed; what fell back
to English). A missing input is reported as missing rather than failing the
step: the PR that says "run interrupted, 40 jobs still queued" is exactly the
one that most needs a body.

    venv/bin/python3 cl10n/ci_report.py --plan plan.json --queue l10n/queue/queue.json \
        --render render.json -o pr-body.md

No provider, no network, no secrets — safe to run in any step.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [_HERE, os.path.join(os.path.dirname(_HERE), "app")]


def _load(path: str | None) -> dict | None:
    if not path or not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None


def build_body(plan: dict | None, queue: dict | None, render: dict | None) -> str:
    lines: list[str] = ["## Continuous localization run", ""]

    if plan:
        actions = plan.get("actions", {})
        lines += [
            f"Planned against `{plan.get('source_commit', '?')[:12]}` — "
            f"{plan.get('documents', '?')} document(s), "
            f"languages: {', '.join(plan.get('langs', []))}.",
            "",
            "| segments | count |",
            "| --- | ---: |",
            f"| new (`TRANSLATE`) | {actions.get('TRANSLATE', 0)} |",
            f"| revised (`REVISE`) | {actions.get('REVISE', 0)} |",
            f"| reused (`REUSE` + `RECHECK`) | "
            f"{actions.get('REUSE', 0) + actions.get('RECHECK', 0)} |",
            f"| copied verbatim (`COPY`) | {actions.get('COPY', 0)} |",
            f"| retired (`RETIRE`) | {actions.get('RETIRE', 0)} |",
            "",
            f"{plan.get('jobs', 0)} job(s) enqueued "
            f"({plan.get('translation_memory_hits', 0)} unit(s) already in the "
            "translation memory).",
        ]
        restored = plan.get("restored_entries") or {}
        if restored:
            lines.append(
                "Recovered from a previous incomplete run without re-billing: "
                + ", ".join(f"{lang}: {n}" for lang, n in sorted(restored.items()))
                + "."
            )
    else:
        lines.append("_No plan report found._")
    lines.append("")

    if queue:
        states = Counter(job["state"] for job in queue.get("jobs", []))
        total = sum(states.values())
        lines += [
            f"**Execution** (`{queue.get('run_id', '?')}`): "
            f"{states.get('done', 0)}/{total} done"
            + (f", {states['rejected']} rejected" if states.get("rejected") else "")
            + (
                f", **{states.get('pending', 0) + states.get('failed', 0) + states.get('in_flight', 0)} "
                "not finished — the next run resumes them; nothing is re-billed**"
                if states.get("pending") or states.get("failed") or states.get("in_flight")
                else ""
            )
            + ".",
            "",
        ]

    if render:
        summary = render.get("summary", render)
        lines += [
            f"**Rendered**: {summary.get('files_rendered', 0)} file(s), "
            f"{summary.get('translated', 0)}/{summary.get('units', 0)} unit(s) translated, "
            f"{summary.get('opaque', 0)} opaque block(s) carried verbatim.",
        ]
        if summary.get("fallbacks"):
            lines.append(
                f"⚠️ {summary['fallbacks']} unit(s) rendered as **English fallback** — "
                "either still queued or rejected; they will be retried on the next run."
            )
        if summary.get("violations"):
            lines.append(
                f"🛑 {summary['violations']} placeholder violation(s) — see the run log."
            )
        if summary.get("retired_entries"):
            lines.append(
                f"{len(summary['retired_entries'])} stale translation-memory "
                "entr(y/ies) garbage-collected."
            )
    else:
        lines.append("_No render report found — the run may have stopped before rendering._")

    lines += [
        "",
        "---",
        "Generated by the `cl10n` workflow. The translation memory "
        "(`l10n/tm/`) in this diff **is** the translations — reviewing it is "
        "reviewing them.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the localization PR body.")
    parser.add_argument("--plan", default=None, help="plan --report output")
    parser.add_argument("--queue", default=None, help="the executed queue file")
    parser.add_argument("--render", default=None, help="render --report output")
    parser.add_argument("-o", "--out", default=None, help="write here (default: stdout)")
    args = parser.parse_args(argv)

    body = build_body(_load(args.plan), _load(args.queue), _load(args.render))
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(body)
    else:
        print(body, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
